"use client";

import { useCallback, useEffect, useMemo, useState, startTransition } from "react";
import {
  Check,
  Clock3,
  ExternalLink,
  FileText,
  Loader2,
  Network,
  Plus,
  Save,
  Trash2,
} from "lucide-react";

import ArchitectureViewer from "@/components/architecture/ArchitectureViewer";
import Unit311DetailMarkdownViewer from "@/components/testflighthub/Unit311DetailMarkdownViewer";
import { useInternalOperationsBasePath } from "./InternalOperationsBasePathContext";
import WorkspaceArchitectureDiagramModal from "./WorkspaceArchitectureDiagramModal";
import type {
  ArchitectureCatalogEntry,
  ArchitectureDiagramDocument,
  SystemArchitectureDiagram,
} from "@/lib/architecture-diagram-data";
import { ARCHITECTURE_DIAGRAM_CATALOG } from "@/lib/architecture-diagram-data";
import {
  groupCategoriesIntoRows,
  type Unit311DetailCategory,
  type Unit311DetailTask,
} from "@/lib/unit311-details-data";
import { findDocPackForCategory } from "@/lib/unit311-details-doc-packs";
import { cn } from "@/lib/utils";

/** Regenerated by `npm run diagram:vercel-architecture` from docs/VERCEL_ARCHITECTURE.md */
const VERCEL_ARCHITECTURE_SVG_HREF = "/architecture/vercel-architecture.svg";
/** Regenerated by `npm run diagram:github-architecture` from docs/GITHUB_ARCHITECTURE.md */
const GITHUB_ARCHITECTURE_SVG_HREF = "/architecture/github-architecture.svg";

type SectionView = "documentation" | "architecture" | "history";
type DetailTab = "details" | "tasks" | "documents";

type OverviewResponse = {
  rootFolderId: string;
  categories: Unit311DetailCategory[];
  folders: Record<string, string>;
  contents: Record<string, string>;
  tasks: Record<string, Unit311DetailTask[]>;
};

type PackDocument = {
  id: string;
  title: string;
  fileName: string;
  order: number;
  fileId: string | null;
  content: string;
};

async function readApiJson<T>(response: Response): Promise<T> {
  const text = await response.text();
  if (!text) throw new Error(`Request failed (${response.status})`);
  try {
    return JSON.parse(text) as T;
  } catch {
    const trimmed = text.trimStart();
    if (trimmed.startsWith("<!DOCTYPE") || trimmed.startsWith("<html")) {
      throw new Error(
        response.ok
          ? "Invalid server response."
          : `Request failed (${response.status}). The Unit311 details API is unavailable.`,
      );
    }
    throw new Error(response.ok ? "Invalid server response." : text.slice(0, 180));
  }
}

function createTask(title: string): Unit311DetailTask {
  return {
    id: crypto.randomUUID(),
    title: title.trim(),
    done: false,
    createdAt: new Date().toISOString(),
  };
}

function formatTimestamp(value: string | null | undefined) {
  if (!value) return "—";
  try {
    return new Intl.DateTimeFormat(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    }).format(new Date(value));
  } catch {
    return value;
  }
}

export default function Unit311DetailsWorkspace() {
  const basePath = useInternalOperationsBasePath();
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [creatingSection, setCreatingSection] = useState(false);
  const [showAddSection, setShowAddSection] = useState(false);
  const [newSectionName, setNewSectionName] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [categories, setCategories] = useState<Unit311DetailCategory[]>([]);
  const [selectedCategoryId, setSelectedCategoryId] = useState<string | null>(null);
  const [sectionView, setSectionView] = useState<SectionView>("documentation");
  const [activeTab, setActiveTab] = useState<DetailTab>("details");
  const [folderIds, setFolderIds] = useState<Record<string, string>>({});
  const [contents, setContents] = useState<Record<string, string>>({});
  const [tasksByCategory, setTasksByCategory] = useState<Record<string, Unit311DetailTask[]>>({});
  const [draft, setDraft] = useState("");
  const [taskDraft, setTaskDraft] = useState<Unit311DetailTask[]>([]);
  const [newTaskTitle, setNewTaskTitle] = useState("");
  const [legacyArchitectureModalOpen, setLegacyArchitectureModalOpen] = useState(false);
  const [diagramLoading, setDiagramLoading] = useState(false);
  const [diagramCreating, setDiagramCreating] = useState(false);
  const [diagram, setDiagram] = useState<SystemArchitectureDiagram | null>(null);
  const [diagramCatalog, setDiagramCatalog] = useState<ArchitectureCatalogEntry[]>([
    ...ARCHITECTURE_DIAGRAM_CATALOG,
  ]);
  const [existingDiagrams, setExistingDiagrams] = useState<
    Array<Pick<SystemArchitectureDiagram, "sectionSlug" | "title" | "updatedAt">>
  >([]);
  const [docsNotice, setDocsNotice] = useState<string | null>(null);
  /** When set, Architecture Diagrams hub shows this diagram on the RHS while keeping the list on the LHS. */
  const [hubActiveDiagramSlug, setHubActiveDiagramSlug] = useState<string | null>(null);
  const [packDocuments, setPackDocuments] = useState<PackDocument[]>([]);
  const [packLabel, setPackLabel] = useState<string | null>(null);
  const [activePackDocId, setActivePackDocId] = useState<string | null>(null);
  const [packLoading, setPackLoading] = useState(false);

  const categoryRows = useMemo(() => groupCategoriesIntoRows(categories), [categories]);
  const isSupabaseSection = selectedCategoryId === "supabase";
  const isVercelSection = selectedCategoryId === "vercel";
  const isGithubSection = selectedCategoryId === "github";
  const isSoftwareAssetRegisterSection = selectedCategoryId === "software-asset-register";

  const selectedCategory = useMemo(
    () => categories.find((category) => category.id === selectedCategoryId) ?? null,
    [categories, selectedCategoryId],
  );

  const isArchitectureDiagramsHub = useMemo(() => {
    if (!selectedCategory) return selectedCategoryId === "architecture-diagrams";
    const label = selectedCategory.label.trim().toLowerCase();
    const folder = selectedCategory.folderName.trim().toLowerCase();
    return (
      selectedCategory.id === "architecture-diagrams" ||
      selectedCategory.id === "custom-architecture-diagrams" ||
      label === "architecture diagrams" ||
      folder === "architecture diagrams"
    );
  }, [selectedCategory, selectedCategoryId]);

  const isDocPackSection = useMemo(() => {
    if (!selectedCategory && !selectedCategoryId) return false;
    return Boolean(
      findDocPackForCategory({
        categoryId: selectedCategory?.id ?? selectedCategoryId,
        label: selectedCategory?.label,
        folderName: selectedCategory?.folderName,
      }),
    );
  }, [selectedCategory, selectedCategoryId]);

  const selectedFolderId = selectedCategoryId ? folderIds[selectedCategoryId] : undefined;
  const activePackDocument =
    packDocuments.find((doc) => doc.id === activePackDocId) ?? packDocuments[0] ?? null;

  const loadOverview = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/unit311-details", { cache: "no-store" });
      const data = await readApiJson<OverviewResponse & { error?: string }>(response);
      if (!response.ok) throw new Error(data.error ?? "Failed to load Unit311 details");

      setCategories(data.categories ?? []);
      setFolderIds(data.folders ?? {});
      setContents(data.contents ?? {});
      setTasksByCategory(data.tasks ?? {});
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : "Failed to load Unit311 details");
    } finally {
      setLoading(false);
    }
  }, []);

  const loadDiagramIndex = useCallback(async () => {
    try {
      const listResponse = await fetch("/api/architecture-diagrams?catalog=1", {
        cache: "no-store",
      });
      const listData = await readApiJson<{
        diagrams?: SystemArchitectureDiagram[];
        catalog?: ArchitectureCatalogEntry[];
        error?: string;
      }>(listResponse);
      if (!listResponse.ok) return;
      setExistingDiagrams(
        (listData.diagrams ?? []).map((item) => ({
          sectionSlug: item.sectionSlug,
          title: item.title,
          updatedAt: item.updatedAt,
        })),
      );
      if (listData.catalog?.length) setDiagramCatalog(listData.catalog);
    } catch {
      // Non-blocking — index is best-effort.
    }
  }, []);

  const loadDocPack = useCallback(async (category: Unit311DetailCategory, sync = false) => {
    setPackLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams({
        category: category.id,
        label: category.label,
      });
      if (sync) params.set("sync", "1");
      const response = await fetch(`/api/unit311-details/documents?${params.toString()}`, {
        cache: "no-store",
      });
      const data = await readApiJson<{
        pack?: { id: string; label: string } | null;
        documents?: PackDocument[];
        error?: string;
      }>(response);
      if (!response.ok) throw new Error(data.error ?? "Failed to load documentation pack");
      let docs = (data.documents ?? []).slice().sort((a, b) => a.order - b.order);
      if (docs.length === 0 && !sync) {
        const syncResponse = await fetch("/api/unit311-details/documents", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ category: category.id, label: category.label }),
        });
        const syncData = await readApiJson<{
          documents?: PackDocument[];
          error?: string;
        }>(syncResponse);
        if (!syncResponse.ok) {
          throw new Error(syncData.error ?? "Failed to sync documentation pack");
        }
        docs = (syncData.documents ?? []).slice().sort((a, b) => a.order - b.order);
      }
      setPackLabel(data.pack?.label ?? category.label);
      setPackDocuments(docs);
      setActivePackDocId((current) => {
        if (current && docs.some((doc) => doc.id === current)) return current;
        return docs[0]?.id ?? null;
      });
    } catch (loadError) {
      setError(
        loadError instanceof Error ? loadError.message : "Failed to load documentation pack",
      );
      setPackDocuments([]);
      setPackLabel(null);
      setActivePackDocId(null);
    } finally {
      setPackLoading(false);
    }
  }, []);

  const loadDiagram = useCallback(async (sectionSlug: string) => {
    setDiagramLoading(true);
    setError(null);
    try {
      const response = await fetch(
        `/api/architecture-diagrams?section=${encodeURIComponent(sectionSlug)}&catalog=1`,
        { cache: "no-store" },
      );
      const data = await readApiJson<{
        diagram?: SystemArchitectureDiagram | null;
        catalog?: ArchitectureCatalogEntry[];
        error?: string;
      }>(response);
      if (!response.ok) throw new Error(data.error ?? "Failed to load architecture diagram");
      setDiagram(data.diagram ?? null);
      if (data.catalog?.length) setDiagramCatalog(data.catalog);
      await loadDiagramIndex();
    } catch (loadError) {
      setDiagram(null);
      setError(
        loadError instanceof Error ? loadError.message : "Failed to load architecture diagram",
      );
    } finally {
      setDiagramLoading(false);
    }
  }, [loadDiagramIndex]);

  useEffect(() => {
    startTransition(() => {
      void loadOverview();
    });
  }, [loadOverview]);

  useEffect(() => {
    startTransition(() => {
      if (!selectedCategoryId) {
        setDraft("");
        setTaskDraft([]);
        setDiagram(null);
        return;
      }
      setDraft(contents[selectedCategoryId] ?? "");
      setTaskDraft((tasksByCategory[selectedCategoryId] ?? []).map((task) => ({ ...task })));
    });
  }, [contents, selectedCategoryId, tasksByCategory]);

  useEffect(() => {
    if (!selectedCategoryId) return;
    if (isArchitectureDiagramsHub) {
      if (sectionView !== "architecture" || !hubActiveDiagramSlug) return;
      startTransition(() => {

        void loadDiagram(hubActiveDiagramSlug);

      });
      return;
    }
    if (sectionView === "documentation") return;
    startTransition(() => {

      void loadDiagram(selectedCategoryId);

    });
  }, [
    hubActiveDiagramSlug,
    isArchitectureDiagramsHub,
    loadDiagram,
    sectionView,
    selectedCategoryId,
  ]);

  useEffect(() => {
    if (!isArchitectureDiagramsHub) return;
    startTransition(() => {
      void loadDiagramIndex();
    });
  }, [isArchitectureDiagramsHub, loadDiagramIndex]);

  useEffect(() => {
    if (!isDocPackSection || !selectedCategory) return;
    if (sectionView !== "documentation") return;
    startTransition(() => {
      void loadDocPack(selectedCategory, false);
    });
  }, [isDocPackSection, loadDocPack, sectionView, selectedCategory]);

  const handleSelectCategory = useCallback((categoryId: string) => {
    setSelectedCategoryId(categoryId);
    setSectionView("documentation");
    const pack = findDocPackForCategory({ categoryId });
    setActiveTab(pack ? "documents" : "details");
    setNewTaskTitle("");
    setSuccessMessage(null);
    setError(null);
    setHubActiveDiagramSlug(null);
    setActivePackDocId(null);
    setPackDocuments([]);
    setPackLabel(null);
  }, []);

  const handleSave = useCallback(async () => {
    if (!selectedCategoryId) return;

    setSaving(true);
    setError(null);
    setSuccessMessage(null);

    try {
      if (activeTab === "tasks") {
        const response = await fetch("/api/unit311-details", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ category: selectedCategoryId, tasks: taskDraft }),
        });

        const data = await readApiJson<{ error?: string; tasksFileName?: string; taskCount?: number }>(
          response,
        );
        if (!response.ok) throw new Error(data.error ?? "Failed to save tasks");

        setTasksByCategory((current) => ({ ...current, [selectedCategoryId]: taskDraft }));
        setSuccessMessage(
          data.taskCount && data.taskCount > 0
            ? `Saved ${data.taskCount} task${data.taskCount === 1 ? "" : "s"}`
            : "Tasks saved",
        );
        return;
      }

      const response = await fetch("/api/unit311-details", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ category: selectedCategoryId, content: draft }),
      });

      const data = await readApiJson<{ error?: string; docxFileName?: string }>(response);
      if (!response.ok) throw new Error(data.error ?? "Failed to save details");

      setContents((current) => ({ ...current, [selectedCategoryId]: draft }));
      setSuccessMessage(data.docxFileName ? `Saved ${data.docxFileName}` : "Details saved");
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : "Failed to save");
    } finally {
      setSaving(false);
    }
  }, [activeTab, draft, selectedCategoryId, taskDraft]);

  const handleCreateSection = useCallback(async () => {
    const name = newSectionName.trim();
    if (!name) {
      setError("Enter a section name.");
      return;
    }

    setCreatingSection(true);
    setError(null);
    setSuccessMessage(null);

    try {
      const response = await fetch("/api/unit311-details/sections", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name }),
      });

      const data = await readApiJson<{
        category?: Unit311DetailCategory;
        folderId?: string;
        error?: string;
      }>(response);

      if (!response.ok || !data.category || !data.folderId) {
        throw new Error(data.error ?? "Failed to create section.");
      }

      setCategories((current) => [...current, data.category!]);
      setFolderIds((current) => ({ ...current, [data.category!.id]: data.folderId! }));
      setContents((current) => ({ ...current, [data.category!.id]: "" }));
      setTasksByCategory((current) => ({ ...current, [data.category!.id]: [] }));
      setSelectedCategoryId(data.category.id);
      setSectionView("documentation");
      setActiveTab("details");
      setNewSectionName("");
      setShowAddSection(false);
      setSuccessMessage(`Added section "${data.category.label}"`);
    } catch (createError) {
      setError(createError instanceof Error ? createError.message : "Failed to create section.");
    } finally {
      setCreatingSection(false);
    }
  }, [newSectionName]);

  const handleCreateDiagram = useCallback(async () => {
    if (!selectedCategoryId || !selectedCategory) return;
    setDiagramCreating(true);
    setError(null);
    setSuccessMessage(null);
    try {
      const catalogEntry = ARCHITECTURE_DIAGRAM_CATALOG.find(
        (entry) => entry.sectionSlug === selectedCategoryId,
      );
      const seedTemplate = catalogEntry?.seedTemplate ?? "blank";
      const response = await fetch("/api/architecture-diagrams", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sectionSlug: selectedCategoryId,
          title:
            catalogEntry?.title ||
            (selectedCategoryId === "platform-overview"
              ? "Platform Overview"
              : `${selectedCategory.label} Architecture`),
          seedTemplate,
        }),
      });
      const data = await readApiJson<{ diagram?: SystemArchitectureDiagram; error?: string }>(
        response,
      );
      if (!response.ok || !data.diagram) {
        throw new Error(data.error ?? "Failed to create diagram.");
      }
      setDiagram(data.diagram);
      setExistingDiagrams((current) => {
        if (current.some((item) => item.sectionSlug === data.diagram!.sectionSlug)) {
          return current.map((item) =>
            item.sectionSlug === data.diagram!.sectionSlug
              ? {
                  sectionSlug: data.diagram!.sectionSlug,
                  title: data.diagram!.title,
                  updatedAt: data.diagram!.updatedAt,
                }
              : item,
          );
        }
        return [
          ...current,
          {
            sectionSlug: data.diagram!.sectionSlug,
            title: data.diagram!.title,
            updatedAt: data.diagram!.updatedAt,
          },
        ];
      });
      setSectionView("architecture");
      setSuccessMessage(`Created ${data.diagram.title}`);
    } catch (createError) {
      setError(createError instanceof Error ? createError.message : "Failed to create diagram.");
    } finally {
      setDiagramCreating(false);
    }
  }, [selectedCategory, selectedCategoryId]);

  const handleOpenSoftwareAssetArchitecture = useCallback(async () => {
    setSelectedCategoryId("software-asset-register");
    setError(null);
    setSuccessMessage(null);
    setDocsNotice(null);
    setDiagramCreating(true);
    try {
      const response = await fetch("/api/architecture-diagrams", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sectionSlug: "software-asset-register",
          title: "Software Asset Register Architecture",
          seedTemplate: "software-asset-register",
        }),
      });
      const data = await readApiJson<{ diagram?: SystemArchitectureDiagram; error?: string }>(
        response,
      );
      if (!response.ok || !data.diagram) {
        throw new Error(data.error ?? "Failed to open Software Asset Register architecture.");
      }
      setDiagram(data.diagram);
      await loadDiagramIndex();
      setSectionView("architecture");
      setSuccessMessage("Opened Software Asset Register architecture diagram.");
    } catch (openError) {
      setError(
        openError instanceof Error
          ? openError.message
          : "Failed to open Software Asset Register architecture.",
      );
    } finally {
      setDiagramCreating(false);
    }
  }, [loadDiagramIndex]);

  const handleSelectArchitectureDiagram = useCallback(
    async (nextSlug: string) => {
      // Stay on the Architecture Diagrams hub — keep the list visible on the LHS.
      if (
        selectedCategoryId === "architecture-diagrams" ||
        selectedCategoryId === "custom-architecture-diagrams" ||
        selectedCategory?.label.trim().toLowerCase() === "architecture diagrams"
      ) {
        setHubActiveDiagramSlug(nextSlug);
        setSectionView("architecture");
        setSuccessMessage(null);
        setError(null);
        setDocsNotice(null);
        await loadDiagram(nextSlug);
        return;
      }

      const match = categories.find((category) => category.id === nextSlug);
      if (match) {
        setSelectedCategoryId(match.id);
        setHubActiveDiagramSlug(null);
        setSectionView("architecture");
        setSuccessMessage(null);
        setError(null);
        setDocsNotice(null);
        return;
      }

      setSelectedCategoryId(nextSlug);
      setHubActiveDiagramSlug(null);
      setSectionView("architecture");
      setDocsNotice(null);
      await loadDiagram(nextSlug);
    },
    [categories, loadDiagram, selectedCategory, selectedCategoryId],
  );

  const handleDiagramChange = useCallback(
    async (nextDoc: ArchitectureDiagramDocument) => {
      if (!diagram) return;
      const sectionSlug = diagram.sectionSlug || hubActiveDiagramSlug || selectedCategoryId;
      if (!sectionSlug) return;

      setDiagram((current) =>
        current ? { ...current, diagramJson: nextDoc, updatedAt: new Date().toISOString() } : current,
      );
      try {
        await fetch("/api/architecture-diagrams", {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            sectionSlug,
            title: diagram.title,
            diagramJson: nextDoc,
          }),
        });
      } catch {
        // Non-blocking autosave failures — user can retry by adjusting the diagram.
      }
    },
    [diagram, hubActiveDiagramSlug, selectedCategoryId],
  );

  const handleLinkToFiles = useCallback(() => {
    if (!selectedFolderId) return;
    const url = new URL(window.location.href);
    url.pathname = basePath;
    url.searchParams.set("view", "files-internal");
    url.searchParams.set("folderId", selectedFolderId);
    window.location.assign(url.toString());
  }, [basePath, selectedFolderId]);

  const handleAddTask = useCallback(() => {
    const title = newTaskTitle.trim();
    if (!title) return;
    setTaskDraft((current) => [...current, createTask(title)]);
    setNewTaskTitle("");
  }, [newTaskTitle]);

  const handleToggleTask = useCallback((taskId: string) => {
    setTaskDraft((current) =>
      current.map((task) => (task.id === taskId ? { ...task, done: !task.done } : task)),
    );
  }, []);

  const handleDeleteTask = useCallback((taskId: string) => {
    setTaskDraft((current) => current.filter((task) => task.id !== taskId));
  }, []);

  const handleUpdateTaskTitle = useCallback((taskId: string, title: string) => {
    setTaskDraft((current) =>
      current.map((task) => (task.id === taskId ? { ...task, title } : task)),
    );
  }, []);

  const sectionHeaderActions = (
    <div className="inline-flex flex-wrap gap-1 rounded-xl border border-white/10 bg-[#0b1524] p-1">
      {(
        [
          { id: "documentation", label: "Edit Notes", icon: FileText },
          { id: "architecture", label: "View Architecture", icon: Network },
          { id: "history", label: "History", icon: Clock3 },
        ] as const
      ).map((action) => {
        const Icon = action.icon;
        const active = sectionView === action.id;
        return (
          <button
            key={action.id}
            type="button"
            onClick={() => {
              setSectionView(action.id);
              setSuccessMessage(null);
              setError(null);
            }}
            className={cn(
              "inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm font-medium transition-colors",
              active
                ? "bg-emerald-600 text-white shadow-sm"
                : "text-white/60 hover:text-white",
            )}
          >
            <Icon className="h-3.5 w-3.5" />
            {action.label}
          </button>
        );
      })}
    </div>
  );

  return (
    <div className="flex min-h-[calc(100dvh-14rem)] flex-col gap-4">
      {error && (
        <p className="rounded-xl border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-200">
          {error}
        </p>
      )}

      {successMessage && (
        <p className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">
          {successMessage}
        </p>
      )}

      <section className="shrink-0 space-y-3 rounded-2xl border border-white/15 bg-white/[0.04] p-4 shadow-[0_24px_64px_rgba(0,0,0,0.45),inset_0_1px_0_rgba(255,255,255,0.08)] backdrop-blur-xl sm:p-5">
        {categoryRows.map((row, rowIndex) => (
          <div key={rowIndex} className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">
            {row.map((category) => {
              const isSelected = selectedCategoryId === category.id;

              return (
                <button
                  key={category.id}
                  type="button"
                  onClick={() => handleSelectCategory(category.id)}
                  className={cn(
                    "min-h-11 rounded-xl border px-3 py-2 text-sm font-medium transition-colors",
                    isSelected
                      ? "border-emerald-600 bg-emerald-600 text-white shadow-sm"
                      : "border-slate-200 bg-white text-slate-900 hover:bg-slate-50",
                  )}
                >
                  {category.label}
                </button>
              );
            })}
          </div>
        ))}

        <div className="border-t border-white/10 pt-3">
          {showAddSection ? (
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
              <input
                value={newSectionName}
                onChange={(event) => setNewSectionName(event.target.value)}
                placeholder="Section name, e.g. AWS, Stripe, Domain registrar…"
                className="min-w-0 flex-1 rounded-xl border border-white/10 bg-[#0b1524] px-4 py-2.5 text-sm text-white outline-none focus:border-sky-400/50"
                onKeyDown={(event) => {
                  if (event.key === "Enter") {
                    event.preventDefault();
                    void handleCreateSection();
                  }
                }}
              />
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => void handleCreateSection()}
                  disabled={creatingSection}
                  className="inline-flex items-center gap-2 rounded-xl border border-emerald-500/40 bg-emerald-600 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  {creatingSection ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <Plus className="h-4 w-4" />
                  )}
                  Add section
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setShowAddSection(false);
                    setNewSectionName("");
                  }}
                  className="rounded-xl border border-white/15 bg-white/[0.06] px-4 py-2.5 text-sm font-medium text-white transition hover:bg-white/[0.1]"
                >
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <button
              type="button"
              onClick={() => {
                setShowAddSection(true);
                setError(null);
                setSuccessMessage(null);
              }}
              className="inline-flex items-center gap-2 rounded-xl border border-dashed border-white/20 bg-white/[0.03] px-4 py-2.5 text-sm font-medium text-white/80 transition hover:border-sky-400/40 hover:bg-white/[0.06] hover:text-white"
            >
              <Plus className="h-4 w-4" />
              Add section
            </button>
          )}
        </div>
      </section>

      <section className="flex min-h-0 flex-1 flex-col rounded-2xl border border-white/15 bg-white/[0.04] p-4 shadow-[0_24px_64px_rgba(0,0,0,0.45),inset_0_1px_0_rgba(255,255,255,0.08)] backdrop-blur-xl sm:p-5">
        {loading ? (
          <div className="flex flex-1 items-center justify-center text-sm text-white/60">
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Loading details…
          </div>
        ) : !selectedCategory && !(selectedCategoryId && sectionView === "architecture") ? (
          <div className="flex flex-1 items-center justify-center text-sm text-white/50">
            Select a category above to view documentation and architecture.
          </div>
        ) : (
          <>
            <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
              <h3 className="text-base font-semibold text-white">
                {selectedCategory?.label ??
                  diagramCatalog.find((entry) => entry.sectionSlug === selectedCategoryId)?.title ??
                  selectedCategoryId}
              </h3>
              {sectionHeaderActions}
            </div>

            {isArchitectureDiagramsHub && sectionView !== "history" ? (
              <div className="grid min-h-[28rem] flex-1 gap-4 lg:grid-cols-[minmax(240px,320px)_minmax(0,1fr)]">
                <aside className="flex min-h-0 flex-col rounded-xl border border-white/10 bg-[#0b1524]/70">
                  <div className="border-b border-white/10 px-4 py-3">
                    <p className="text-sm font-medium text-white">Diagrams</p>
                    <p className="mt-0.5 text-[11px] text-white/45">
                      Select a blueprint to open it on the right.
                    </p>
                  </div>
                  <div className="min-h-0 flex-1 overflow-y-auto">
                    {existingDiagrams.length === 0 ? (
                      <p className="px-4 py-8 text-center text-sm text-white/45">
                        No architecture diagrams have been created yet.
                      </p>
                    ) : (
                      <ul className="divide-y divide-white/10">
                        {existingDiagrams
                          .slice()
                          .sort((a, b) => a.title.localeCompare(b.title))
                          .map((item) => {
                            const catalogEntry = diagramCatalog.find(
                              (entry) => entry.sectionSlug === item.sectionSlug,
                            );
                            const isActive = hubActiveDiagramSlug === item.sectionSlug;
                            return (
                              <li key={item.sectionSlug}>
                                <button
                                  type="button"
                                  onClick={() =>
                                    void handleSelectArchitectureDiagram(item.sectionSlug)
                                  }
                                  className={cn(
                                    "flex w-full items-start justify-between gap-3 px-4 py-3 text-left transition-colors",
                                    isActive
                                      ? "bg-sky-500/15"
                                      : "hover:bg-white/[0.04]",
                                  )}
                                >
                                  <div className="min-w-0">
                                    <p className="truncate text-sm font-medium text-white">
                                      {item.title}
                                    </p>
                                    <p className="mt-0.5 truncate text-xs text-white/45">
                                      {catalogEntry?.description || item.sectionSlug}
                                    </p>
                                  </div>
                                  <Network
                                    className={cn(
                                      "mt-0.5 h-3.5 w-3.5 shrink-0",
                                      isActive ? "text-sky-200" : "text-white/35",
                                    )}
                                  />
                                </button>
                              </li>
                            );
                          })}
                      </ul>
                    )}
                  </div>
                </aside>

                <div className="flex min-h-0 min-w-0 flex-col">
                  {!hubActiveDiagramSlug ? (
                    <div className="flex flex-1 flex-col items-center justify-center rounded-xl border border-dashed border-white/15 bg-[#0b1524]/40 px-6 text-center">
                      <Network className="h-8 w-8 text-sky-300/80" />
                      <p className="mt-4 text-sm font-medium text-white/85">
                        Select a diagram from the list
                      </p>
                      <p className="mt-2 max-w-sm text-sm text-white/45">
                        The list stays on the left so you can switch between living architecture
                        diagrams without leaving this section.
                      </p>
                    </div>
                  ) : diagramLoading ? (
                    <div className="flex flex-1 items-center justify-center text-sm text-white/60">
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Loading architecture…
                    </div>
                  ) : diagram && diagram.sectionSlug === hubActiveDiagramSlug ? (
                    <div className="space-y-3">
                      {docsNotice ? (
                        <p className="rounded-xl border border-amber-400/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-100">
                          {docsNotice}
                        </p>
                      ) : null}
                      <ArchitectureViewer
                        title={diagram.title}
                        sectionSlug={diagram.sectionSlug}
                        diagramDocument={diagram.diagramJson}
                        catalog={diagramCatalog}
                        existingDiagrams={existingDiagrams}
                        knownDocSections={categories.map((category) => category.id)}
                        height="min(72vh, 760px)"
                        onDocumentChange={(next) => void handleDiagramChange(next)}
                        onSelectDiagram={(slug) => void handleSelectArchitectureDiagram(slug)}
                        onNodeDocNavigate={(slug) => {
                          const match = categories.find((category) => category.id === slug);
                          if (match) {
                            setDocsNotice(null);
                            handleSelectCategory(match.id);
                            setSectionView("documentation");
                            return;
                          }
                          setDocsNotice("Documentation coming soon");
                        }}
                      />
                    </div>
                  ) : (
                    <div className="flex flex-1 items-center justify-center rounded-xl border border-dashed border-white/15 bg-[#0b1524]/40 px-6 text-center text-sm text-white/50">
                      Diagram unavailable. Try another item from the list.
                    </div>
                  )}
                </div>
              </div>
            ) : null}

            {sectionView === "documentation" && selectedCategory && !isArchitectureDiagramsHub ? (
              <>
                {isSoftwareAssetRegisterSection ? (
                  <div className="mb-4 rounded-xl border border-emerald-400/25 bg-emerald-500/10 p-4">
                    <p className="text-sm font-medium text-emerald-100">
                      Software Asset Register architecture
                    </p>
                    <p className="mt-1 text-xs leading-relaxed text-emerald-100/70">
                      Live editable diagram of the Corporate Information register — APIs, encrypted
                      credentials, file attachments, and future Financials hooks.
                    </p>
                    <button
                      type="button"
                      onClick={() => void handleOpenSoftwareAssetArchitecture()}
                      disabled={diagramCreating}
                      className="mt-3 inline-flex items-center gap-2 rounded-xl border border-emerald-400/40 bg-emerald-600 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-60"
                    >
                      {diagramCreating ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <Network className="h-4 w-4" />
                      )}
                      Open live architecture diagram
                    </button>
                  </div>
                ) : null}

                <div className="mb-3 inline-flex rounded-xl border border-white/10 bg-[#0b1524] p-1">
                  {(
                    [
                      ...(isDocPackSection
                        ? ([{ id: "documents", label: "Documents" }] as const)
                        : []),
                      { id: "details", label: isDocPackSection ? "Index notes" : "details" },
                      { id: "tasks", label: "tasks" },
                    ] as const
                  ).map((tab) => (
                    <button
                      key={tab.id}
                      type="button"
                      onClick={() => {
                        setActiveTab(tab.id);
                        setSuccessMessage(null);
                        setError(null);
                      }}
                      className={cn(
                        "rounded-lg px-4 py-1.5 text-sm font-medium capitalize transition-colors",
                        activeTab === tab.id
                          ? "bg-emerald-600 text-white shadow-sm"
                          : "text-white/60 hover:text-white",
                      )}
                    >
                      {tab.label}
                    </button>
                  ))}
                </div>

                {activeTab === "documents" && isDocPackSection ? (
                  <div className="grid min-h-[28rem] flex-1 gap-4 lg:grid-cols-[minmax(240px,320px)_minmax(0,1fr)]">
                    <aside className="flex min-h-0 flex-col rounded-xl border border-white/10 bg-[#0b1524]/70">
                      <div className="border-b border-white/10 px-4 py-3">
                        <p className="text-sm font-medium text-white">
                          {packLabel ?? selectedCategory.label}
                        </p>
                        <p className="mt-0.5 text-[11px] text-white/45">
                          Select a document to open it on the right.
                        </p>
                      </div>
                      <div className="min-h-0 flex-1 overflow-y-auto">
                        {packLoading ? (
                          <div className="flex items-center gap-2 px-4 py-8 text-sm text-white/55">
                            <Loader2 className="h-4 w-4 animate-spin" />
                            Loading documents…
                          </div>
                        ) : packDocuments.length === 0 ? (
                          <div className="space-y-3 px-4 py-8 text-center">
                            <p className="text-sm text-white/45">No documents synced yet.</p>
                            <button
                              type="button"
                              onClick={() => void loadDocPack(selectedCategory, true)}
                              className="inline-flex items-center gap-2 rounded-xl border border-sky-400/35 bg-sky-500/15 px-3 py-2 text-xs font-semibold text-sky-100"
                            >
                              Sync documentation pack
                            </button>
                          </div>
                        ) : (
                          <ul className="divide-y divide-white/10">
                            {packDocuments.map((doc) => {
                              const isActive = activePackDocument?.id === doc.id;
                              return (
                                <li key={doc.id}>
                                  <button
                                    type="button"
                                    onClick={() => setActivePackDocId(doc.id)}
                                    className={cn(
                                      "flex w-full items-start gap-3 px-4 py-3 text-left transition-colors",
                                      isActive ? "bg-sky-500/15" : "hover:bg-white/[0.04]",
                                    )}
                                  >
                                    <FileText
                                      className={cn(
                                        "mt-0.5 h-3.5 w-3.5 shrink-0",
                                        isActive ? "text-sky-200" : "text-white/35",
                                      )}
                                    />
                                    <div className="min-w-0">
                                      <p className="truncate text-sm font-medium text-white">
                                        {doc.title}
                                      </p>
                                      <p className="mt-0.5 truncate text-[11px] text-white/40">
                                        {doc.fileName}
                                      </p>
                                    </div>
                                  </button>
                                </li>
                              );
                            })}
                          </ul>
                        )}
                      </div>
                    </aside>

                    <div className="flex min-h-0 min-w-0 flex-col">
                      {packLoading ? (
                        <div className="flex flex-1 items-center justify-center text-sm text-white/60">
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                          Loading document…
                        </div>
                      ) : activePackDocument ? (
                        <Unit311DetailMarkdownViewer content={activePackDocument.content} />
                      ) : (
                        <div className="flex flex-1 flex-col items-center justify-center rounded-xl border border-dashed border-white/15 bg-[#0b1524]/40 px-6 text-center">
                          <FileText className="h-8 w-8 text-sky-300/80" />
                          <p className="mt-4 text-sm font-medium text-white/85">
                            Select a document from the list
                          </p>
                        </div>
                      )}
                    </div>
                  </div>
                ) : activeTab === "details" ? (
                  <textarea
                    value={draft}
                    onChange={(event) => setDraft(event.target.value)}
                    placeholder={`Enter ${selectedCategory.label} details, links, credentials, and notes…`}
                    className="min-h-[18rem] flex-1 resize-y rounded-xl border border-white/10 bg-[#0b1524] px-4 py-3 text-sm leading-relaxed text-white outline-none focus:border-sky-400/50"
                  />
                ) : (
                  <div className="flex min-h-[18rem] flex-1 flex-col">
                    <div className="flex gap-2">
                      <input
                        value={newTaskTitle}
                        onChange={(event) => setNewTaskTitle(event.target.value)}
                        placeholder="Add a task…"
                        className="min-w-0 flex-1 rounded-xl border border-white/10 bg-[#0b1524] px-4 py-2.5 text-sm text-white outline-none focus:border-sky-400/50"
                        onKeyDown={(event) => {
                          if (event.key === "Enter") {
                            event.preventDefault();
                            handleAddTask();
                          }
                        }}
                      />
                      <button
                        type="button"
                        onClick={handleAddTask}
                        disabled={!newTaskTitle.trim()}
                        className="inline-flex items-center gap-2 rounded-xl border border-emerald-500/40 bg-emerald-600 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-60"
                      >
                        <Plus className="h-4 w-4" />
                        Add
                      </button>
                    </div>

                    {taskDraft.length === 0 ? (
                      <p className="mt-6 text-sm text-white/45">No tasks yet. Add one above.</p>
                    ) : (
                      <ul className="mt-4 divide-y divide-white/10 rounded-xl border border-white/10 bg-[#0b1524]/60">
                        {taskDraft.map((task) => (
                          <li key={task.id} className="flex items-center gap-3 px-4 py-3">
                            <button
                              type="button"
                              onClick={() => handleToggleTask(task.id)}
                              aria-label={task.done ? "Mark task incomplete" : "Mark task complete"}
                              className={cn(
                                "flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border transition-colors",
                                task.done
                                  ? "border-emerald-500/50 bg-emerald-500/20 text-emerald-200"
                                  : "border-white/15 bg-white/[0.04] text-white/40 hover:border-white/25",
                              )}
                            >
                              {task.done ? <Check className="h-3.5 w-3.5" /> : null}
                            </button>
                            <input
                              value={task.title}
                              onChange={(event) =>
                                handleUpdateTaskTitle(task.id, event.target.value)
                              }
                              className={cn(
                                "min-w-0 flex-1 bg-transparent text-sm outline-none",
                                task.done ? "text-white/45 line-through" : "text-white/90",
                              )}
                            />
                            <button
                              type="button"
                              onClick={() => handleDeleteTask(task.id)}
                              aria-label={`Delete task ${task.title}`}
                              title={`Delete task ${task.title}`}
                              className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-red-400/30 bg-red-500/10 text-red-200 transition-colors hover:border-red-400/50 hover:bg-red-500/20"
                            >
                              <Trash2 className="h-3.5 w-3.5" />
                            </button>
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                )}

                <div className="mt-4 flex flex-wrap items-center gap-3">
                  {activeTab !== "documents" ? (
                  <button
                    type="button"
                    onClick={() => void handleSave()}
                    disabled={saving}
                    className="inline-flex items-center gap-2 rounded-xl border border-emerald-500/40 bg-emerald-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-60"
                  >
                    {saving ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Save className="h-4 w-4" />
                    )}
                    Save
                  </button>
                  ) : (
                  <button
                    type="button"
                    onClick={() => selectedCategory && void loadDocPack(selectedCategory, true)}
                    disabled={packLoading || !selectedCategory}
                    className="inline-flex items-center gap-2 rounded-xl border border-sky-400/35 bg-sky-500/15 px-4 py-2 text-sm font-medium text-sky-100 transition hover:bg-sky-500/25 disabled:cursor-not-allowed disabled:opacity-60"
                  >
                    {packLoading ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <FileText className="h-4 w-4" />
                    )}
                    Re-sync from repository
                  </button>
                  )}

                  <button
                    type="button"
                    onClick={handleLinkToFiles}
                    disabled={!selectedFolderId}
                    className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/[0.06] px-4 py-2 text-sm font-medium text-white transition hover:bg-white/[0.1] disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    <ExternalLink className="h-4 w-4" />
                    Link to files
                  </button>

                  {isSupabaseSection ? (
                    <button
                      type="button"
                      onClick={() => setLegacyArchitectureModalOpen(true)}
                      className="inline-flex items-center gap-2 rounded-xl border border-sky-400/30 bg-sky-500/15 px-4 py-2 text-sm font-medium text-sky-100 transition hover:bg-sky-500/25"
                    >
                      <Network className="h-4 w-4" />
                      Legacy workspace diagram
                    </button>
                  ) : null}

                  {isVercelSection ? (
                    <a
                      href={VERCEL_ARCHITECTURE_SVG_HREF}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-2 rounded-xl border border-sky-400/30 bg-sky-500/15 px-4 py-2 text-sm font-medium text-sky-100 transition hover:bg-sky-500/25"
                    >
                      <Network className="h-4 w-4" />
                      Vercel SVG
                    </a>
                  ) : null}

                  {isGithubSection ? (
                    <a
                      href={GITHUB_ARCHITECTURE_SVG_HREF}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-2 rounded-xl border border-sky-400/30 bg-sky-500/15 px-4 py-2 text-sm font-medium text-sky-100 transition hover:bg-sky-500/25"
                    >
                      <Network className="h-4 w-4" />
                      Github SVG
                    </a>
                  ) : null}

                  {isSoftwareAssetRegisterSection ? (
                    <button
                      type="button"
                      onClick={() => void handleOpenSoftwareAssetArchitecture()}
                      disabled={diagramCreating}
                      className="inline-flex items-center gap-2 rounded-xl border border-sky-400/30 bg-sky-500/15 px-4 py-2 text-sm font-medium text-sky-100 transition hover:bg-sky-500/25 disabled:opacity-60"
                    >
                      {diagramCreating ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <Network className="h-4 w-4" />
                      )}
                      Live architecture diagram
                    </button>
                  ) : null}
                </div>
              </>
            ) : null}

            {sectionView === "documentation" && !selectedCategory ? (
              <div className="flex min-h-[12rem] items-center justify-center rounded-xl border border-dashed border-white/15 bg-[#0b1524]/40 px-4 text-center text-sm text-white/50">
                Documentation coming soon for this architecture topic.
              </div>
            ) : null}

            {sectionView === "architecture" && !isArchitectureDiagramsHub ? (
              diagramLoading ? (
                <div className="flex min-h-[20rem] flex-1 items-center justify-center text-sm text-white/60">
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Loading architecture…
                </div>
              ) : diagram ? (
                <div className="space-y-3">
                  {docsNotice ? (
                    <p className="rounded-xl border border-amber-400/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-100">
                      {docsNotice}
                    </p>
                  ) : null}
                  <ArchitectureViewer
                    title={diagram.title}
                    sectionSlug={diagram.sectionSlug}
                    diagramDocument={diagram.diagramJson}
                    catalog={diagramCatalog}
                    existingDiagrams={existingDiagrams}
                    knownDocSections={categories.map((category) => category.id)}
                    height="min(72vh, 760px)"
                    onDocumentChange={(next) => void handleDiagramChange(next)}
                    onSelectDiagram={(slug) => void handleSelectArchitectureDiagram(slug)}
                    onNodeDocNavigate={(slug) => {
                      const match = categories.find((category) => category.id === slug);
                      if (match) {
                        setDocsNotice(null);
                        handleSelectCategory(match.id);
                        setSectionView("documentation");
                        return;
                      }
                      setDocsNotice("Documentation coming soon");
                    }}
                  />
                </div>
              ) : (
                <div className="flex min-h-[20rem] flex-1 flex-col items-center justify-center rounded-2xl border border-dashed border-white/15 bg-[#0b1524]/40 px-6 text-center">
                  <Network className="h-8 w-8 text-sky-300/80" />
                  <p className="mt-4 text-sm font-medium text-white/85">
                    No architecture diagram has been created yet.
                  </p>
                  <p className="mt-2 max-w-md text-sm text-white/45">
                    Create an editable React Flow blueprint for{" "}
                    {selectedCategory?.label ?? "this section"}. Platform Overview and Storage use
                    seeded templates.
                  </p>
                  <button
                    type="button"
                    onClick={() => void handleCreateDiagram()}
                    disabled={diagramCreating}
                    className="mt-5 inline-flex items-center gap-2 rounded-xl border border-emerald-500/40 bg-emerald-600 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-emerald-500 disabled:opacity-60"
                  >
                    {diagramCreating ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Plus className="h-4 w-4" />
                    )}
                    Create Diagram
                  </button>
                </div>
              )
            ) : null}

            {sectionView === "history" && selectedCategory ? (
              <div className="rounded-2xl border border-white/10 bg-[#0b1524]/50 p-5">
                <h4 className="text-sm font-semibold text-white">Section history</h4>
                <p className="mt-1 text-sm text-white/45">
                  Lightweight change log for this knowledge-centre section. Full version history can
                  be layered on later.
                </p>
                <dl className="mt-5 space-y-3 text-sm">
                  <div className="flex flex-wrap items-baseline justify-between gap-2 border-b border-white/10 pb-3">
                    <dt className="text-white/50">Documentation notes</dt>
                    <dd className="text-white/85">
                      {contents[selectedCategory.id]?.trim()
                        ? "Present in workspace files"
                        : "No notes saved yet"}
                    </dd>
                  </div>
                  <div className="flex flex-wrap items-baseline justify-between gap-2 border-b border-white/10 pb-3">
                    <dt className="text-white/50">Architecture diagram</dt>
                    <dd className="text-white/85">
                      {diagram ? diagram.title : "Not created"}
                    </dd>
                  </div>
                  <div className="flex flex-wrap items-baseline justify-between gap-2 border-b border-white/10 pb-3">
                    <dt className="text-white/50">Diagram created</dt>
                    <dd className="text-white/85">{formatTimestamp(diagram?.createdAt)}</dd>
                  </div>
                  <div className="flex flex-wrap items-baseline justify-between gap-2">
                    <dt className="text-white/50">Diagram updated</dt>
                    <dd className="text-white/85">{formatTimestamp(diagram?.updatedAt)}</dd>
                  </div>
                </dl>
                {!diagram && sectionView === "history" ? (
                  <button
                    type="button"
                    onClick={() => setSectionView("architecture")}
                    className="mt-5 text-sm font-medium text-sky-300 hover:text-sky-200"
                  >
                    Open architecture view
                  </button>
                ) : null}
              </div>
            ) : null}
          </>
        )}
      </section>

      <WorkspaceArchitectureDiagramModal
        open={legacyArchitectureModalOpen}
        onClose={() => setLegacyArchitectureModalOpen(false)}
      />
    </div>
  );
}
